import { Helmet } from 'react-helmet-async';
import { LegalPageLayout } from './LegalPageLayout';

export default function TermsOfService() {
  return (
    <>
      <Helmet>
        <title>Terms of Service - CompliPack</title>
        <meta name="description" content="CompliPack Terms of Service - Read our terms and conditions for using our EU compliance documentation platform." />
      </Helmet>
      
      <LegalPageLayout title="Terms of Service" lastUpdated="February 4, 2026">
        <section id="acceptance" className="mb-12">
          <h2 className="text-2xl font-semibold text-foreground mb-4">1. Acceptance of Terms</h2>
          <p className="text-muted-foreground leading-relaxed mb-4">
            By accessing or using CompliPack ("Service", "Platform", "we", "us", "our"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the Service.
          </p>
          <p className="text-muted-foreground leading-relaxed">
            CompliPack is operated by CompliPack Ltd., a company registered in Hungary.
          </p>
        </section>

        <section id="description" className="mb-12">
          <h2 className="text-2xl font-semibold text-foreground mb-4">2. Description of Service</h2>
          <p className="text-muted-foreground leading-relaxed mb-4">
            CompliPack provides software tools for generating compliance documentation related to EU packaging regulations (PPWR) and Digital Product Passport (DPP) requirements.
          </p>
          
          <div className="bg-amber-500/10 border border-amber-500/30 rounded-xl p-6 my-6">
            <h3 className="font-semibold text-foreground mb-3">⚠️ IMPORTANT LIMITATIONS</h3>
            <ul className="space-y-3 text-muted-foreground">
              <li>
                <strong className="text-foreground">NOT LEGAL ADVICE:</strong> CompliPack does not provide legal advice, regulatory guidance, or compliance consulting. Our tools generate documentation based on user-provided data but do not guarantee regulatory compliance.
              </li>
              <li>
                <strong className="text-foreground">NOT OFFICIAL CERTIFICATION:</strong> Reports generated by CompliPack are NOT official certifications, stamps of approval, or regulatory clearances. They are documentation tools for internal record-keeping.
              </li>
              <li>
                <strong className="text-foreground">NOT DIGITAL PRODUCT PASSPORTS:</strong> CompliPack does not issue official EU Digital Product Passports as defined by EU regulations. We provide DPP-ready structured documentation to help users prepare for DPP requirements.
              </li>
              <li>
                <strong className="text-foreground">USER RESPONSIBILITY:</strong> You are solely responsible for ensuring accuracy of all data you input, verifying compliance with applicable laws, consulting legal and regulatory experts, and meeting all EU regulatory obligations.
              </li>
              <li>
                <strong className="text-foreground">NO GUARANTEE:</strong> We do not guarantee that use of CompliPack will result in regulatory compliance or prevent fines, penalties, or legal action.
              </li>
            </ul>
          </div>
        </section>

        <section id="accounts" className="mb-12">
          <h2 className="text-2xl font-semibold text-foreground mb-4">3. User Accounts</h2>
          <ul className="space-y-3 text-muted-foreground">
            <li><strong className="text-foreground">Registration:</strong> You must provide accurate, current, and complete information during registration. You are responsible for maintaining the confidentiality of your account credentials.</li>
            <li><strong className="text-foreground">Eligibility:</strong> You must be at least 18 years old and legally capable of entering into binding contracts to use this Service.</li>
            <li><strong className="text-foreground">Business Use:</strong> CompliPack is intended for business and professional use only. You represent that you are using the Service for legitimate business purposes.</li>
            <li><strong className="text-foreground">Account Security:</strong> You are responsible for all activity under your account. Notify us immediately of any unauthorized access.</li>
            <li><strong className="text-foreground">Account Termination:</strong> We reserve the right to suspend or terminate accounts that violate these Terms or engage in fraudulent, abusive, or illegal activity.</li>
          </ul>
        </section>

        <section id="billing" className="mb-12">
          <h2 className="text-2xl font-semibold text-foreground mb-4">4. Subscription Plans & Billing</h2>
          <ul className="space-y-3 text-muted-foreground">
            <li><strong className="text-foreground">Plans:</strong> CompliPack offers multiple subscription tiers (Basic, Standard, Pro, Enterprise) with different features and usage limits as described on our pricing page.</li>
            <li><strong className="text-foreground">Free Trial:</strong> New users receive a 14-day free trial. No credit card required for trial. You may cancel anytime during trial without charge.</li>
            <li><strong className="text-foreground">Billing:</strong> Subscriptions are billed monthly in advance. Fees are non-refundable except as required by law.</li>
            <li><strong className="text-foreground">Auto-Renewal:</strong> Subscriptions automatically renew unless canceled before the renewal date. You will be charged the then-current rate.</li>
            <li><strong className="text-foreground">Cancellation:</strong> You may cancel your subscription anytime from your account settings. Cancellation takes effect at the end of the current billing period.</li>
            <li><strong className="text-foreground">Price Changes:</strong> We may change subscription prices with 30 days' notice. Continued use after notice constitutes acceptance of new prices.</li>
            <li><strong className="text-foreground">Payment Processor:</strong> Payments are processed by Stripe. You agree to Stripe's terms and conditions.</li>
          </ul>
        </section>

        <section id="user-data" className="mb-12">
          <h2 className="text-2xl font-semibold text-foreground mb-4">5. User Data & Content</h2>
          <ul className="space-y-3 text-muted-foreground">
            <li><strong className="text-foreground">Your Data:</strong> You retain ownership of all data you input into CompliPack (product information, dimensions, materials, etc.).</li>
            <li><strong className="text-foreground">License to Us:</strong> You grant CompliPack a limited, non-exclusive license to use your data to provide the Service (perform calculations, generate reports, display information pages).</li>
            <li><strong className="text-foreground">Data Accuracy:</strong> You are solely responsible for the accuracy, quality, and legality of your data. We are not responsible for errors resulting from inaccurate input.</li>
            <li><strong className="text-foreground">Prohibited Content:</strong> You may not input data that violates laws, infringes intellectual property rights, contains malicious code, or misrepresents product characteristics.</li>
            <li><strong className="text-foreground">Data Deletion:</strong> Upon account deletion, we will delete your data within 30 days, except as required for legal, accounting, or backup purposes.</li>
          </ul>
        </section>

        <section id="ip" className="mb-12">
          <h2 className="text-2xl font-semibold text-foreground mb-4">6. Intellectual Property</h2>
          <ul className="space-y-3 text-muted-foreground">
            <li><strong className="text-foreground">Platform Ownership:</strong> CompliPack owns all rights to the platform, including software, algorithms, designs, trademarks, and content (excluding your data).</li>
            <li><strong className="text-foreground">Restrictions:</strong> You may not copy, modify, or reverse engineer the platform, remove copyright notices, use CompliPack branding without permission, create derivative works, or resell the Service.</li>
            <li><strong className="text-foreground">Feedback:</strong> Any suggestions or feedback you provide becomes our property and may be used without compensation to you.</li>
          </ul>
        </section>

        <section id="acceptable-use" className="mb-12">
          <h2 className="text-2xl font-semibold text-foreground mb-4">7. Acceptable Use Policy</h2>
          <p className="text-muted-foreground leading-relaxed mb-4">You agree NOT to:</p>
          <ul className="space-y-2 text-muted-foreground list-disc list-inside">
            <li>Use the Service for illegal purposes</li>
            <li>Attempt to gain unauthorized access to systems or data</li>
            <li>Interfere with Service operation or other users</li>
            <li>Use automated tools to scrape or harvest data (except via official API)</li>
            <li>Impersonate others or provide false information</li>
            <li>Transmit malware, viruses, or harmful code</li>
            <li>Violate any applicable laws or regulations</li>
            <li>Use the Service to generate fraudulent or misleading compliance claims</li>
          </ul>
          <p className="text-muted-foreground leading-relaxed mt-4">
            Violation may result in immediate account termination.
          </p>
        </section>

        <section id="disclaimers" className="mb-12">
          <h2 className="text-2xl font-semibold text-foreground mb-4">8. Disclaimers & Limitation of Liability</h2>
          
          <div className="bg-destructive/10 border border-destructive/30 rounded-xl p-6 my-6">
            <h3 className="font-semibold text-foreground mb-3">⚖️ CRITICAL LEGAL PROTECTION</h3>
            
            <h4 className="font-medium text-foreground mt-4 mb-2">"AS IS" SERVICE</h4>
            <p className="text-muted-foreground mb-4">
              CompliPack is provided "AS IS" and "AS AVAILABLE" without warranties of any kind, express or implied, including but not limited to merchantability, fitness for particular purpose, non-infringement, accuracy or reliability, regulatory compliance, or uninterrupted or error-free operation.
            </p>

            <h4 className="font-medium text-foreground mt-4 mb-2">NO COMPLIANCE GUARANTEE</h4>
            <p className="text-muted-foreground mb-4 uppercase font-semibold">
              WE DO NOT GUARANTEE THAT USE OF COMPLIPACK WILL RESULT IN COMPLIANCE WITH EU REGULATIONS OR PREVENT FINES, PENALTIES, OR LEGAL ACTION.
            </p>

            <h4 className="font-medium text-foreground mt-4 mb-2">LIMITATION OF LIABILITY</h4>
            <p className="text-muted-foreground mb-4">
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, CompliPack, its officers, directors, employees, and agents SHALL NOT BE LIABLE FOR:
            </p>
            <ul className="space-y-2 text-muted-foreground list-disc list-inside mb-4">
              <li>Any fines, penalties, or legal consequences resulting from regulatory non-compliance</li>
              <li>Any indirect, incidental, consequential, special, or punitive damages</li>
              <li>Loss of profits, revenue, data, or business opportunities</li>
              <li>Any damages arising from use or inability to use the Service</li>
              <li>Damages caused by errors, inaccuracies, or omissions in reports</li>
              <li>Third-party actions based on your use of CompliPack</li>
            </ul>
            <p className="text-muted-foreground font-semibold">
              OUR TOTAL LIABILITY TO YOU SHALL NOT EXCEED THE AMOUNT YOU PAID TO COMPLIPACK IN THE 12 MONTHS PRECEDING THE CLAIM, OR €100, WHICHEVER IS LESS.
            </p>
          </div>

          <h4 className="font-medium text-foreground mt-6 mb-2">Indemnification</h4>
          <p className="text-muted-foreground leading-relaxed">
            You agree to indemnify and hold CompliPack harmless from any claims, damages, losses, or expenses (including legal fees) arising from your use of the Service, your violation of these Terms, your violation of laws or regulations, inaccuracy of data you provide, or third-party claims related to your use of reports.
          </p>
        </section>

        <section id="modifications" className="mb-12">
          <h2 className="text-2xl font-semibold text-foreground mb-4">9. Modifications to Service & Terms</h2>
          <ul className="space-y-3 text-muted-foreground">
            <li><strong className="text-foreground">Service Changes:</strong> We reserve the right to modify, suspend, or discontinue any part of the Service at any time with or without notice.</li>
            <li><strong className="text-foreground">Terms Updates:</strong> We may update these Terms periodically. Material changes will be notified via email or platform notice 30 days in advance. Continued use constitutes acceptance.</li>
            <li><strong className="text-foreground">No Obligation:</strong> We have no obligation to maintain any features or provide updates, but may do so at our discretion.</li>
          </ul>
        </section>

        <section id="termination" className="mb-12">
          <h2 className="text-2xl font-semibold text-foreground mb-4">10. Termination</h2>
          <ul className="space-y-3 text-muted-foreground">
            <li><strong className="text-foreground">By You:</strong> Cancel your subscription anytime from account settings.</li>
            <li><strong className="text-foreground">By Us:</strong> We may suspend or terminate your account for violation of these Terms, non-payment, illegal or fraudulent activity, or abusive behavior toward staff or other users.</li>
            <li><strong className="text-foreground">Effect of Termination:</strong> Upon termination, access to Service ends immediately, your data will be deleted within 30 days, no refunds for prepaid periods (except as required by law), and Sections 5, 6, 8, 11, and 12 survive termination.</li>
          </ul>
        </section>

        <section id="privacy" className="mb-12">
          <h2 className="text-2xl font-semibold text-foreground mb-4">11. Privacy & Data Protection</h2>
          <p className="text-muted-foreground leading-relaxed">
            Your use of CompliPack is subject to our <a href="/legal/privacy" className="text-primary hover:underline">Privacy Policy</a>, which is incorporated by reference into these Terms. By using the Service, you consent to data practices described in our Privacy Policy. CompliPack complies with EU GDPR regulations.
          </p>
        </section>

        <section id="disputes" className="mb-12">
          <h2 className="text-2xl font-semibold text-foreground mb-4">12. Dispute Resolution</h2>
          <ul className="space-y-3 text-muted-foreground">
            <li><strong className="text-foreground">Governing Law:</strong> These Terms are governed by the laws of Hungary and the European Union, without regard to conflict of law principles.</li>
            <li><strong className="text-foreground">Jurisdiction:</strong> Any disputes arising from these Terms or use of the Service shall be resolved in the courts of Hungary.</li>
            <li><strong className="text-foreground">Informal Resolution:</strong> Before filing any claim, you agree to attempt informal resolution by contacting support@complipack.io.</li>
            <li><strong className="text-foreground">Class Action Waiver:</strong> You agree to resolve disputes individually and waive the right to participate in class actions or representative proceedings.</li>
          </ul>
        </section>

        <section id="general" className="mb-12">
          <h2 className="text-2xl font-semibold text-foreground mb-4">13. General Provisions</h2>
          <ul className="space-y-3 text-muted-foreground">
            <li><strong className="text-foreground">Entire Agreement:</strong> These Terms, together with our Privacy Policy and Cookie Policy, constitute the entire agreement between you and CompliPack.</li>
            <li><strong className="text-foreground">Severability:</strong> If any provision is found invalid, the remaining provisions remain in full effect.</li>
            <li><strong className="text-foreground">Waiver:</strong> Failure to enforce any provision does not waive our right to enforce it later.</li>
            <li><strong className="text-foreground">Assignment:</strong> You may not assign these Terms. We may assign to affiliates or in connection with a merger/acquisition.</li>
            <li><strong className="text-foreground">Force Majeure:</strong> We are not liable for delays or failures due to circumstances beyond reasonable control.</li>
            <li><strong className="text-foreground">Language:</strong> These Terms are provided in English. Translations are for convenience only. English version controls in case of conflict.</li>
          </ul>
        </section>

        <section id="contact" className="mb-12">
          <h2 className="text-2xl font-semibold text-foreground mb-4">14. Contact Information</h2>
          <p className="text-muted-foreground leading-relaxed mb-4">For questions about these Terms:</p>
          <ul className="space-y-2 text-muted-foreground">
            <li><strong className="text-foreground">Email:</strong> legal@complipack.io</li>
            <li><strong className="text-foreground">Support:</strong> support@complipack.io</li>
          </ul>
        </section>

        <div className="border-t border-border pt-8 mt-12">
          <p className="text-center text-muted-foreground italic">
            By using CompliPack, you acknowledge that you have read, understood, and agree to be bound by these Terms of Service.
          </p>
        </div>
      </LegalPageLayout>
    </>
  );
}
